version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - 127.0.0.1:3333:3306
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
       MYSQL_USER: <%= ENV['DATABASE_DOCKER_USER'] %>
       MYSQL_ROOT_PASSWORD: <%= ENV['DATABASE_DOCKER_PASSWORD'] %>
       MYSQL_ROOT_HOST: <%= ENV['DATABASE_DEV_HOST'] %>
    env_file:
      - ./.env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./.env
